/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemInfo */

#ifndef _Included_SystemInfo
#define _Included_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemInfo
 * Method:    getCpuInfo
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_SystemInfo_getCpuInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
